In [1]:
from pydataset import data
import numpy as np
import math
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns
%matplotlib inline
import pandas as pd
import env

In [2]:
from sklearn.metrics import confusion_matrix

##### 1. Create a new file named model_evaluation for these exercises.

In [14]:
# done

##### 2. Evaluate the model's performance

a. In the context of this problem, what is a false positive?

b. In the context of this problem, what is a false negative?

c. How would you describe this model?

In [3]:
# ACCURACY
def accuracy(TP, FP, FN, TN):
    return (TP+TN)/(TP+TN+FP+FN)

# PRECISION
def precision(TP, FP, FN, TN): 
    return TP/(TP+FP)

# RECALL
def recall(TP, FP, FN, TN):
    return TP/(TP+FN)

In [16]:
# TP = 46 
# FP = 13 
# FN = 7
# TN = 34 


In [63]:
# ACCURACY
accuracy(46, 13, 7, 34)

0.8

In [19]:
# RECALL
recall(46, 13, 7, 34)

0.8679245283018868

In [20]:
# PRECISION
precision(46, 13, 7, 34)

0.7796610169491526

##### a. In the context of this problem, what is a false positive?

In [ ]:
# predicted dog, actually cat

##### b. In the context of this problem, what is a false negative?

In [ ]:
# predicted cat, actually dog

##### c. How would you describe this model?

##### 3. You are working as a datascientist working for Codeup Cody Creator (C3 for short), a rubber-duck manufacturing plant. Unfortunately, some of the rubber ducks that are produced will have defects. Your team has built several models that try to predict those defects.

Use the predictions dataset and pandas to help answer the following questions:

a. An internal team wants to investigate the cause of the manufacturing defects. They tell you that they want to identify as many of the ducks that have a defect as possible. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

b. Recently several stories in the local news have come out highlighting customers who received a rubber duck with a defect, and portraying C3 in a bad light. The PR team has decided to launch a program that gives customers with a defective duck a vacation to Hawaii. They need you to predict which ducks will have defects, but tell you the really don't want to accidentally give out a vacation package when the duck really doesn't have a defect. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

In [25]:
df = pd.read_csv('/Users/adriananuncio/Documents/CodeUp/c3.csv')

In [27]:
df

actual     model1     model2     model3
0    No Defect  No Defect     Defect  No Defect
1    No Defect  No Defect     Defect     Defect
2    No Defect  No Defect     Defect  No Defect
3    No Defect     Defect     Defect     Defect
4    No Defect  No Defect     Defect  No Defect
..         ...        ...        ...        ...
195  No Defect  No Defect     Defect     Defect
196     Defect     Defect  No Defect  No Defect
197  No Defect  No Defect  No Defect  No Defect
198  No Defect  No Defect     Defect     Defect
199  No Defect  No Defect  No Defect     Defect

[200 rows x 4 columns]

In [28]:
model_1 = pd.crosstab(df.actual, df.model1)

model_1_cm = confusion_matrix(df.actual, df.model1,
                 labels = ('Defect', 'No Defect'))

In [29]:
model_1

model1     Defect  No Defect
actual                      
Defect          8          8
No Defect       2        182

In [30]:
model_1_cm

array([[  8,   8],
       [  2, 182]])

In [31]:
model_2 = pd.crosstab(df.actual, df.model2)

model_2_cm = confusion_matrix(df.actual, df.model2,
                 labels = ('Defect', 'No Defect'))

In [32]:
model_2

model2     Defect  No Defect
actual                      
Defect          9          7
No Defect      81        103

In [33]:
model_2_cm

array([[  9,   7],
       [ 81, 103]])

In [34]:
model_3 = pd.crosstab(df.actual, df.model3)

model_3_cm = confusion_matrix(df.actual, df.model3,
                 labels = ('Defect', 'No Defect'))

In [35]:
model_3

model3     Defect  No Defect
actual                      
Defect         13          3
No Defect      86         98

In [36]:
model_3_cm

array([[13,  3],
       [86, 98]])

##### a. An internal team wants to investigate the cause of the manufacturing defects. They tell you that they want to identify as many of the ducks that have a defect as possible. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

In [43]:
# precission

In [37]:
model_3_cm

array([[13,  3],
       [86, 98]])

In [21]:
# model_1

# TP = 8
# FP = 8
# FN = 2
# TN = 182

precision(8, 8, 2, 182)

0.5

In [72]:
# model_2

# TP = 9
# FP = 7
# FN = 81
# TN = 103

In [22]:
precision(9, 7, 81, 103)

0.5625

In [38]:
# model_3

# TP = 13
# FP = 3
# FN = 86
# TN = 98

precision(13, 3, 86, 98)

0.8125

In [39]:
# model_3 would be the most precise model and the model that 
# -- would be the best to use for predicting as many defective 
# -- ducks as possible

##### b. Recently several stories in the local news have come out highlighting customers who received a rubber duck with a defect, and portraying C3 in a bad light. The PR team has decided to launch a program that gives customers with a defective duck a vacation to Hawaii. 
They need you to predict which ducks will have defects, but tell you the really don't want to accidentally give out a vacation package when the duck really doesn't have a defect. 

Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

In [40]:
# recall

In [41]:
# model_1
recall(8, 8, 2, 182)

0.8

In [42]:
# model_2
recall(9, 7, 81, 103)

0.1

In [44]:
# model_3
recall(13, 3, 86, 98)

0.13131313131313133

In [ ]:
# model_1 would be the best selection for identifying 
# -- which ducks will be defective, and avoiding accidentally
# -- giving away a free vacation

##### 4. Given this dataset, use pandas to create a baseline model (i.e. a model that just predicts the most common class) and answer the following questions:

In [4]:
df = pd.read_csv('/Users/adriananuncio/Documents/CodeUp/gives_you_paws.csv')

In [5]:
df

actual model1 model2 model3 model4
0       cat    cat    dog    cat    dog
1       dog    dog    cat    cat    dog
2       dog    cat    cat    cat    dog
3       dog    dog    dog    cat    dog
4       cat    cat    cat    dog    dog
...     ...    ...    ...    ...    ...
4995    dog    dog    dog    dog    dog
4996    dog    dog    cat    cat    dog
4997    dog    cat    cat    dog    dog
4998    cat    cat    cat    cat    dog
4999    dog    dog    dog    dog    dog

[5000 rows x 5 columns]

In [6]:
df.insert(1, 'baseline', 'dog')

In [7]:
df

actual baseline model1 model2 model3 model4
0       cat      dog    cat    dog    cat    dog
1       dog      dog    dog    cat    cat    dog
2       dog      dog    cat    cat    cat    dog
3       dog      dog    dog    dog    cat    dog
4       cat      dog    cat    cat    dog    dog
...     ...      ...    ...    ...    ...    ...
4995    dog      dog    dog    dog    dog    dog
4996    dog      dog    dog    cat    cat    dog
4997    dog      dog    cat    cat    dog    dog
4998    cat      dog    cat    cat    cat    dog
4999    dog      dog    dog    dog    dog    dog

[5000 rows x 6 columns]

In [ ]:
# TP = 13
# FP = 3
# FN = 86
# TN = 98

precision(13, 3, 86, 98)

##### 4a. In terms of accuracy, how do the various models compare to the baseline model? Are any of the models better than the baseline?

In [46]:
# actual x baseline
a_b = pd.crosstab(df['baseline'], df['actual'])

In [47]:
baseline_cm = confusion_matrix(df.actual, df.baseline,
                 labels = ('dog', 'cat'))

In [27]:
accuracy(3254, 1746, 0, 0)

0.6508

In [28]:
precision(3254, 1746, 0, 0)

0.6508

In [29]:
recall(3254, 1746, 0, 0)

1.0

In [55]:
# ACTUAL X BASELINE RESULTS
# -- accuracy = 0.6508
# -- precision = 0.6508
# -- recall = 1.0

In [48]:
# actual x model_1

a_m1 = pd.crosstab(df['model1'], df['actual'])

In [49]:
model1_cm = confusion_matrix(df.actual, df.model1,
                 labels = ('dog', 'cat'))

In [ ]:
# TP = 2614, TN = 1423, FP = 323, FN = 640

In [30]:
accuracy(2614, 1423, 323, 640)

0.6508

In [32]:
precision(2614, 1423, 323, 640)

0.6475105276195194

In [33]:
recall(2614, 1423, 323, 640)

0.8900238338440586

In [56]:
# ACTUAL X MODEL_1
# -- accuracy = 0.6508
# -- precision = 0.6475
# -- recall = 0.8900

In [50]:
# actual x model_2

a_m2 = pd.crosstab(df['model2'], df['actual'])

In [45]:
model2_cm = confusion_matrix(df.actual, df.model2,
                 labels = ('dog', 'cat'))

In [ ]:
# TP = 1597, TN = 1555, FP = 191, FN = 1657

In [34]:
accuracy(1597, 1555, 191, 1657)

0.6508

In [35]:
precision(1597, 1555, 191, 1657)

0.5066624365482234

In [36]:
recall(1597, 1555, 191, 1657)

0.8931767337807607

In [60]:
# ACTUAL X MODEL_2
# -- accuracy = 0.6508
# -- precision = 0.5067
# -- recall = 0.8932

In [51]:
# actual x model_3

a_m3 = pd.crosstab(df['model3'], df['actual'])

In [44]:
model3_cm = confusion_matrix(df.actual, df.model3,
                 labels = ('dog', 'cat'))

In [ ]:
# TP = 1655, TN = 893, FP = 853, FN = 1599

In [37]:
accuracy(1655, 893, 853, 1599)

0.6508

In [38]:
precision(1655, 893, 853, 1599)

0.6495290423861853

In [39]:
recall(1655, 893, 853, 1599)

0.6598883572567783

In [61]:
# ACTUAL X MODEL_3
# -- accuracy = 0.6508
# -- precision = 0.6495
# -- recall = 0.6599

In [52]:
# actual x model_4

a_m4 = pd.crosstab(df['model4'], df['actual'])

In [53]:
model4_cm = confusion_matrix(df.actual, df.model4,
                 labels = ('dog', 'cat'))

In [40]:
# TP = 3110, TN = 603, FP = 1143, FN = 144

In [41]:
accuracy(3110, 603, 1143, 144)

0.6508

In [42]:
precision(3110, 603, 1143, 144)

0.8375976299488285

In [43]:
recall(3110, 603, 1143, 144)

0.7312485304490948

In [62]:
# ACTUAL X MODEL_4
# -- accuracy = 0.6508
# -- precision = 0.8376
# -- recall = 0.7312

In [64]:
# ACTUAL X BASELINE RESULTS
# -- accuracy = 0.6508
# -- precision = 0.6508
# -- recall = 1.0

# ACTUAL X MODEL_1
# -- accuracy = 0.6508
# -- precision = 0.6475
# -- recall = 0.8900

# ACTUAL X MODEL_2
# -- accuracy = 0.6508
# -- precision = 0.5067
# -- recall = 0.8932

# ACTUAL X MODEL_3
# -- accuracy = 0.6508
# -- precision = 0.6495
# -- recall = 0.6599

# ACTUAL X MODEL_4
# -- accuracy = 0.6508
# -- precision = 0.8376
# -- recall = 0.7312


# all models have an equal accuracy rate. 
# Model_4 (precision = 0.8376) is the only model with a better 
# -- precision rate than the baseline (0.6508).
# The baseline had the best recall rate (1.0)

##### 4b. Suppose you are working on a team that solely deals with dog pictures. Which of these models would you recommend?

In [ ]:
# the baseline because it predicts all dogs

##### 4c. Suppose you are working on a team that solely deals with cat pictures. Which of these models would you recommend?